//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Productos
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public string categoria { get; set; }
        public string proveedor { get; set; }
        public string marca { get; set; }
        public string medidas { get; set; }
        public int cantidad { get; set; }
        public decimal precio { get; set; }
    }
}
